### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by Gitoffthelawn** [ashleybaldock/sixornot#11]
I temporarily disabled SixOrNot v2.0.0.1, and experienced a noticeable performance impact.

It's possible it is directly SixOrNot or an interaction with another extension.

I don't have sufficient time to troubleshoot this properly, but I thought you would still appreciate learning of my experience.

**Comment by ashleybaldock** [comment]
Thanks - I was going to take a look at performance issues in the next release so this is a good reminder :)

**Comment by Gitoffthelawn** [comment]
You're welcome.  I actually wound up keeping SixOrNot disabled ☹️ because Firefox felt more responsive without it installed.  I miss it, but I elected more speed over it.  Maybe you'll have success, or maybe I am experiencing the placebo effect. 😃

**Comment by ashleybaldock** [comment]
I think since switching to the WebExtensions API, and changing how the addon keeps track of information performance is hopefully improved.
