### ISSUE TITLE
Blank icon in address bar on macOS

### ISSUE THREAD

**Issue by TheDS** [ashleybaldock/sixornot#15]
On my laptop running macOS 10.13.4 with Firefox 60 and the latest SixOrNot (3.1), I noticed that there's a blank icon for the extension in the address bar. The proper icon does appear on my Windows machine however.

It looks like the problem is that it's trying to use 32x32 size images, but none exist in the "images/32/colour" or "images/32/grey" directories of the XPI. Putting images in those locations makes them show up.

**Before**
<img width="778" alt="screen shot 2018-05-09 at 4 38 58 pm" src="https://user-images.githubusercontent.com/4566142/39841713-584378b4-53a9-11e8-9658-2564f7a8cc6e.png">

**After**
<img width="774" alt="screen shot 2018-05-09 at 4 57 40 pm" src="https://user-images.githubusercontent.com/4566142/39842017-7da49bc8-53aa-11e8-9dad-998d9820e8e5.png">

**Comment by ashleybaldock** [comment]
I guess you have a retina display on your Mac? I had at some point completely forgotten to actually make the 32px version of the icons :) New version including them should go live shortly. Thanks for pointing this out!

**Comment by TheDS** [comment]
Oh, yes, it does have a retina display. That explains the difference. Thank you for the speedy release of 3.1.1!
