### ISSUE TITLE
Icon in address bar disappears for ipv6 sites after a force reload

### ISSUE THREAD

**Issue by Fanolian** [ashleybaldock/sixornot#16]
Welcome back for this useful tool!

Steps to reproduce:
1. Install SixOrNot 3.1.1 in a new profile in Nightly.
2. Enable "Show icon in address bar".
3. Navigate to a ipv6 site, e.g. http://ashley.baldock.me/sixornot, https://ipv6.google.com/. Make sure the icon works for now. (Sometimes it doesn't. I can't figure it out yet.)
4. Force reload the tab. (Shift-click reload button, or Ctrl-F5)

Actual result:
The icon in address bar is gone.

Workaround:
Switch to another tab and back. The icon appears again but it changes to a question mark in a black square.
Sometimes a simple reloads works too.

Note:
In Firefox 60 release, a simple reload at ipv6 sites will also make the icon in address bar disappear.
The issue does not affect ipv4 sites.

**Comment by ashleybaldock** [comment]
Does this only affect the address bar icon, and not the button?

**Comment by ashleybaldock** [comment]
Figured out what was going wrong - 3.1.2 should fix things :)

**Comment by ashleybaldock** [comment]
I believe this is fixed, although no feedback from original reporter, if it's still an issue please let me know :)
