### ISSUE TITLE
SixOrNot icon does not show up in Firefox's about:addons

### ISSUE THREAD

**Issue by cpeterso** [ashleybaldock/sixornot#23]
# Steps to reproduce

1. Install SixOrNot.
2. Open Firefox's `about:addons` page.
3. Scroll down to `about:addons`' entry for SixOrNot.

# Expected result

I expected the "6" icon like that shown on [SixOrNot's addons.mozilla.org page](https://addons.mozilla.org/en-GB/firefox/addon/sixornot/):

![image](https://user-images.githubusercontent.com/629193/120537347-09b26c00-c39a-11eb-853d-6915bd246eb3.png)

# Actual result

Instead of a "6" icon, there is an empty square:

![image](https://user-images.githubusercontent.com/629193/120537047-ade7e300-c399-11eb-93e1-475d541a5670.png)

**Comment by ashleybaldock** [comment]
That's weird. Could you tell me which version of Firefox and OS you're using?

**Comment by cpeterso** [comment]
> That's weird. Could you tell me which version of Firefox and OS you're using?

I'm closing this issue because I don't think this is your bug. :)

I see this behavior in Firefox 90 (Nightly channel) on both Windows 10 and macOS, but the SixOrNot icon loads correctly in a brand new Firefox profile. So there must be some setting in my regular Firefox profile that is breaking the icon load.

btw, your SixOrNot extension is very cool! I only recently enabled IPv6 support on my home LAN and I'm surprised to see which websites which offer IPv6 and which only support IPv4.

**Comment by cpeterso** [comment]
Closing the loop here: I spoke with an addons.mozilla.org developer. He says this looks like an addons.mozilla.org bug (failing to generate some of the extension icons on the server) and asked me to file an addons.mozilla.org bug: https://github.com/mozilla/addons/issues/8362

**Comment by ashleybaldock** [comment]
Thanks for the feedback :) It is amazing how ubiquitous IPv6 is these days, good thing too!
