### ISSUE TITLE
Sometimes shows hosts from previous tab

### ISSUE THREAD

**Issue by Gitoffthelawn** [ashleybaldock/sixornot#5]
Sometimes the Sixornot popup window will show hosts from the previously focused tab in Firefox.

It's usually pretty obvious, so it's not the end of the world, but if you can fix it, great! :-)

Thanks for the great extension!

**Comment by Gitoffthelawn** [comment]
Just an FYI, this continues to be an issue.  Noticing it fairly often.  Any possibility for an update?

**Comment by ashleybaldock** [comment]
Oh, huh, I didn't get a notification when you opened this issue initially. I'll take a look and see if I can fix it.

**Comment by Gitoffthelawn** [comment]
Thanks.  I try to be _very_ patient when it comes to free software.  Perhaps in this case, I was too patient and didn't realize that you didn't get pinged when I posted the issue! :smiley:

**Comment by ashleybaldock** [comment]
I've worked out why this is happening now - working on a fix :)

**Comment by Gitoffthelawn** [comment]
Great.  Thanks! 🎉

**Comment by ashleybaldock** [comment]
This should be fixed in version 2.0.2
