### ISSUE TITLE
Gray question mark appearing incorrectly

### ISSUE THREAD

**Issue by amaurea** [ashleybaldock/sixornot#7]
Quite often a the extension will show a gray question mark even when all the individual hosts listed in the detailed list have a well-defined status. For example, as I'm writing this sixornot shows a gray question mark in the address bar, but all the github-hosts listed individually are ipv4.

This issue may be related to #5, as this seems to happen when the main host (github.com in this case) is missing from the detailed list. So the opposite behavior from #5 when the previously visited page will appear in addition to the normal ones. In both cases refreshing the page typically fixes the issue.

To be more explicit, here's how the list looks when the problem occurs:

* ipv4 assets-cdn.github.com 151.101.32.133
* ipv4 avatars1.githubusercontent.com 151.101.32.133
* ipv4 avatars2.githubusercontent.com 151.101.32.133
* ipv4 avatars3.githubusercontent.com 151.101.32.133
* ipv4 avatars0.githubusercontent.com 151.101.32.133

and here's what it looks like after refreshing, when the button shows a 4 as expected.

* ipv4 github.com 192.30.253.113, 192.30.253.112
* ipv4 assets-cdn.github.com 151.101.32.133
* ipv4 avatars1.githubusercontent.com 151.101.32.133
* etc..

This was with firefox 49.0.2 with https-everywhere, ublock and umatrix active.

**Comment by ashleybaldock** [comment]
This does seem to be essentially the same issue as bug #5 - tracking exactly which requests are linked to which page load became a little harder when switching to the multiprocess versions of Firefox and I guess there's still some bugs in how this is handled to work out.

**Comment by ashleybaldock** [comment]
This should be fixed in version 2.0.2
